import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { withSSRContext } from 'aws-amplify'

export async function getServerSideProps ({ req }) {
  const SSR = withSSRContext({ req })
  const { user } = SSR.Auth
  console.log('SSR User', user)
  return {
    props: {
      SSRuser: user
    }
  }
}

export default function Home({SSRuser}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <p>Test App</p>
          <Link href="/sign-in">Sign In/Profile</Link>
          <div>SSRUser: <pre>{SSRuser}</pre></div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
